/*
 * SECO dynamic configuration
 * Used to write on the standard board's configuration. The newest configuration coming from 
 * an external tool that properly chaing this file
 *
 * This file is automatically generated. Do not edit.
 */

#ifdef ENV_DEFAULT_VIDEO_SETING
#undef ENV_DEFAULT_VIDEO_SETING
#endif
#define ENV_DEFAULT_VIDEO_SETING                 "fdt_overlay_video_list=\0"

#ifdef ENV_DEFAULT_VIDEO_MODE
#undef ENV_DEFAULT_VIDEO_MODE
#endif
#define ENV_DEFAULT_VIDEO_MODE                   "videomode= \0"

#ifdef ENV_DEFAULT_DISPLAY
#undef ENV_DEFAULT_DISPLAY
#endif
#define ENV_DEFAULT_DISPLAY                      "panel=\0"
    

#ifdef ENV_DEFAULT_PERIPHERAL
#undef ENV_DEFAULT_PERIPHERAL
#endif
#define ENV_DEFAULT_PERIPHERAL                      "fdt_overlay_per_list=\0"

